theme: jekyll-theme-cayman
title: Team Vaccine MT
description: You get a vaccine! You get a vaccine! Everyone gets a vaccine!

link_1:
  show: true
  url: http://health.umt.edu/publichealth/
  text: UM School of Public Health

link_2:
  show: true
  url: https://www.cdc.gov
  text: CDC
  
